apiVersion: v1
kind: Service
metadata:
  name: {{ include "pts.fullname" . }}
  labels:
    {{- include "pts.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "pts.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
