apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "pts.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    {{- if include "pts.useKeyVault" . }}
    azure.workload.identity/client-id: {{ required "secrets.keyvault.clientId is required" .Values.secrets.keyvault.clientId | quote }}
    {{- end }}
automountServiceAccountToken: false
